### ISSUE TITLE
Demo with Go backend and Vue frontend

### ISSUE THREAD

**Issue by endlessuniverse** [rocicorp/replicache-todo#2]
Please consider creating a demo with a Go+Supabase backend and Vue frontend that includes blob upload to Supabase buckets.

Supabase modules for Go:
https://github.com/nedpals/supabase-go
https://github.com/overseedio/realtime-go
https://github.com/supabase-community/storage-go

Also it would be awesome if the demo includes the use of fractional indexing and programmatic validation.

In the docs, you mentioned: "If we wanted better control over this, we could use fractional indexing but that's not necessary in this case."

In a forum, you mentioned: "Imagine, for example, a calendaring application. An application built with Replicache can enforce the invariant that a room is only booked by one event in one time slice even under concurrent edits, just using normal programmatic validation. It's hard to do this kind of thing with CRDTs or other approaches to automatic merging because the data model knows nothing about the application's constraints."
https://news.ycombinator.com/item?id=28218719

Thanks a lot!

**Comment by aboodman** [comment]
Hi, thank you for the suggestions. I've split them into many separate bugs as I don't think it makes sense to have them all in the same sample.

Here are some links that may help you until these samples arrive:

* We have a detailed recipe on blobs here: https://doc.replicache.dev/recipes/blobs
* Replidraw has some very basic validation here: https://github.com/rocicorp/replidraw/blob/main/frontend/shape.ts#L62 - it checks if the object has been removed by some other mutation concurrently (eg, a write/delete conflict). You're right it would be good to demonstrate some more sophisticated examples. I've added a bug for that in Replicache (https://github.com/rocicorp/replicache/issues/924).

If you have not seen, we have an OSS JS library that uses fractional indexing: https://github.com/rocicorp/fractional-indexing. It has some usage samples and you can crawl github for examples of other usages.
