### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'digest')

### ISSUE THREAD

**Issue by aidos** [rocicorp/replicache-todo#27]
Hello. I wanted to give Replicache a spin but I'm running into an issue with the [Quickstart](https://doc.replicache.dev/).

When launching the app I get the following error message:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/91913/190894295-f6ed249a-9c1c-4733-a3fd-96cd8d5361a5.png">

Any pointers appreciated.

**Comment by aboodman** [comment]
Argh, this is because crypto.subtle is only defined in 'secure domains'. Every so often a user trips over this, we should have a more clear error message. Filed https://github.com/rocicorp/replicache/issues/1026.
